
export LD_LIBRARY_PATH := ../../:$(LD_LIBRARY_PATH)

CPP=g++
NVCC=nvcc

CUDA_HOME=/home/wfchiang/lib/cuda-6.0
CUDA_SDK_HOME=/home/wfchiang/lib/cuda-6.0-sdk/C

export LD_LIBRARY_PATH := $(CUDA_HOME)/lib64:$(LD_LIBRARY_PATH)


NN=32
BB=32
R=2 
# INPUT_SIZE = NN * BB * 2
INPUT_SIZE=2048
S3FP_DIR=/home/weifan/numerical_precision/s3fp/trunk


all: compile 

compile: fft-32 fft-64

dataio.o: dataio.cpp dataio.h 

fft-32: dataio.o 
	$(NVCC) -DFT=float -DFT2=float2 -Dmake_FT2=make_float2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -c fft.cu -arch=sm_20 

	$(CPP) fft.o dataio.o -o fft-32 -lcuda -lcudart -L $(CUDA_HOME)/lib64 

fft-64: dataio.o 
	$(NVCC) -DFT=double -DFT2=double2 -Dmake_FT2=make_double2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -c fft.cu -arch=sm_20

	$(CPP) fft.o dataio.o -o fft-64 -lcuda -lcudart -L $(CUDA_HOME)/lib64


TIMEOUT=20
RESOURCE=SVE
RSEED=0
FTERROR=REL
REL_DELTA=0.001
CHECK_UNSTABLE_ERROR=false
INPUTLB=-100.0
INPUTUB=100.0


create-base-conf:
	@echo "==== generate s3fp_setting ====" 
	@echo TIMEOUT = $(TIMEOUT) > s3fp_setting
	@echo RESOURCE = $(RESOURCE) >> s3fp_setting
	@echo RSEED = $(RSEED) >> s3fp_setting
	@echo FTERROR = $(FTERROR) >> s3fp_setting
	@echo REL_DELTA = $(REL_DELTA) >> s3fp_setting
	@echo UNIFORM_INPUT = true >> s3fp_setting
	@echo UNIFORM_INPUTLB = $(INPUTLB) >> s3fp_setting
	@echo UNIFORM_INPUTUB = $(INPUTUB) >> s3fp_setting
	@echo N_INPUT_REPEATS = 10 >> s3fp_setting
#	@echo N_OUTPUTS = 10 >> s3fp_setting

test-urt: create-base-conf
	@echo RT = URT >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-bgrt: create-base-conf
	@echo RT = BGRT >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-ils: create-base-conf
	@echo RT = ILS >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-pso: create-base-conf
	@echo RT = PSO >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

clean:
	-rm *~
	-rm *.o 
	-rm fft-32 fft-64 
	-rm __outdump
	-rm best_input_* 
	-rm fft-gpu_input
	-rm fft-gpu_output_*
