
export LD_LIBRARY_PATH := ../../:$(LD_LIBRARY_PATH)

CPP=g++
NVCC=nvcc

QD_HOME=/home/weifan/lib/qd-2.3.14/install
GQD_HOME=/home/weifan/lib/gqd-1.2
CUDA_HOME=/home/weifan/lib/cuda-6.0
CUDA_SDK_HOME=/home/weifan/lib/cuda-4.2-sdk/C

export LD_LIBRARY_PATH := $(CUDA_HOME)/lib64:$(LD_LIBRARY_PATH)


NN=32
BB=32
R=2 
# INPUT_SIZE = NN * BB * 2
INPUT_SIZE=2048
S3FP_DIR=/home/weifan/numerical_precision/s3fp/trunk


all: compile 

compile: fft-32 fft-128 

fft-32: 
	$(NVCC) -DFT=float -DFT2=float2 -Dmake_FT2=make_float2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -I $(QD_HOME)/include -c fft.cu -arch=sm_20 

	$(CPP) -I $(QD_HOME)/include fft.o $(QD_HOME)/lib/libqd.a -o fft-32 -lcuda -lcudart -L $(CUDA_HOME)/lib64 

fft-64: 
	$(NVCC) -DFT=double -DFT2=double2 -Dmake_FT2=make_double2 -DNN=$(NN) -DBB=$(BB) -DR=$(R) -I $(QD_HOME)/include -I $(CUDA_SDK_HOME)/common/inc -c fft.cu -arch=sm_20 

	$(CPP) -I $(QD_HOME)/include fft.o $(QD_HOME)/lib/libqd.a -o fft-64 -lcuda -lcutil_x86_64 -lcudart -L $(CUDA_HOME)/lib64 -L $(CUDA_SDK_HOME)/lib

fft-128:
	$(NVCC) -DNN=$(NN) -DBB=$(BB) -DR=$(R) -I $(QD_HOME)/include -I$(GQD_HOME)/inc -I $(CUDA_SDK_HOME)/common/inc -c fft.128.cu -arch=sm_20 

	$(CPP) -I $(QD_HOME)/include -I $(GQD_HOME)/inc fft.128.o $(QD_HOME)/lib/libqd.a -o fft-128 -lcuda -lcutil_x86_64 -lcudart -L $(CUDA_HOME)/lib64 -L $(CUDA_SDK_HOME)/lib


TIMEOUT=20
RESOURCE=SVE
RSEED=0
FTERROR=REL
REL_DELTA=0.001
CHECK_UNSTABLE_ERROR=false
INPUTLB=-100.0
INPUTUB=100.0


create-base-conf:
	@echo "==== generate s3fp_setting ====" 
	@echo TIMEOUT = $(TIMEOUT) > s3fp_setting
	@echo RESOURCE = $(RESOURCE) >> s3fp_setting
	@echo RSEED = $(RSEED) >> s3fp_setting
	@echo FTERROR = $(FTERROR) >> s3fp_setting
	@echo REL_DELTA = $(REL_DELTA) >> s3fp_setting
	@echo UNIFORM_INPUT = true >> s3fp_setting
	@echo UNIFORM_INPUTLB = $(INPUTLB) >> s3fp_setting
	@echo UNIFORM_INPUTUB = $(INPUTUB) >> s3fp_setting
	@echo N_INPUT_REPEATS = 10 >> s3fp_setting
#	@echo N_OUTPUTS = 10 >> s3fp_setting

test-urt: create-base-conf
	@echo RT = URT >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-bgrt: create-base-conf
	@echo RT = BGRT >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-ils: create-base-conf
	@echo RT = ILS >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

test-pso: create-base-conf
	@echo RT = PSO >> s3fp_setting 
	@echo PARALLELRT = false >> s3fp_setting 
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp-dd 32 $(INPUT_SIZE) fft-gpu_input fft-32 fft-gpu_output_32 fft-128 fft-gpu_output_128 

clean:
	-rm *.o 
	-rm fft-32 fft-64 fft-128 
	-rm __outdump
	-rm best_input
	-rm fft-gpu_input
	-rm fft-gpu_output_*
