
CC=g++

S3FP_DIR=../..

all: compile

INPUT_SIZE=240
EXP=
ifeq ($(INPUT_SIZE),9)
	EXP=EXP1
else ifeq ($(INPUT_SIZE),240)
	EXP=EXP5
else ifeq ($(INPUT_SIZE),960)
	EXP=EXP4
else 
	$(error NO SUCH INPUT SIZE $(INPUT_SIZE))
endif 
TIMEOUT=1000
RESOURCE=SVE # or TIME
RSEED=0
PARALLELRT=true
FTERROR=REL
INPUT_RANGE_FILE=$(INPUT_SIZE)-input-ranges
REL_DELTA=0.001


compile: input_ranges_generator dqmom-32 dqmom-128

dqmom-32:
	$(CC) -o dqmom-32 -DCHECK_BB -DFT=float -D$(EXP) dqmom.cpp 
dqmom-64:
	$(CC) -o dqmom-32 -DCHECK_BB -DFT=double -D$(EXP) dqmom.cpp 
dqmom-128:
	$(CC) -o dqmom-128 -DCHECK_BB -DFT=__float128 -D$(EXP) dqmom.cpp 

input_ranges_generator:
	$(CC) -o input_ranges_generator ./input_ranges_generator.cpp

create-base-conf:
	@echo "==== generate s3fp_setting ====" 
	@echo TIMEOUT = $(TIMEOUT) > s3fp_setting
	@echo RESOURCE = $(RESOURCE) >> s3fp_setting
	@echo RSEED = $(RSEED) >> s3fp_setting
	@echo FTERROR = $(FTERROR) >> s3fp_setting
	@echo REL_DELTA = $(REL_DELTA) >> s3fp_setting
	@echo UNIFORM_INPUT = false >> s3fp_setting
	@echo INPUT_RANGE_FILE = $(INPUT_RANGE_FILE) >> s3fp_setting
	@echo PARALLELRT = $(PARALLELRT) >> s3fp_setting 

test-urt: create-base-conf input_ranges_generator
	@echo RT = URT >> s3fp_setting 
	@echo "==== generate input ranges ===="
	@input_ranges_generator $(INPUT_SIZE) $(INPUT_RANGE_FILE)
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp 32 $(INPUT_SIZE) dqmom_input dqmom-32 dqmom_output_32 dqmom-128 dqmom_output_128  

test-bgrt: create-base-conf input_ranges_generator
	@echo RT = BGRT >> s3fp_setting 
	@echo "==== generate input ranges ===="
	@input_ranges_generator $(INPUT_SIZE) $(INPUT_RANGE_FILE)
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp 32 $(INPUT_SIZE) dqmom_input dqmom-32 dqmom_output_32 dqmom-128 dqmom_output_128  

test-ils: create-base-conf input_ranges_generator
	@echo RT = ILS >> s3fp_setting 
	@echo "==== generate input ranges ===="
	@input_ranges_generator $(INPUT_SIZE) $(INPUT_RANGE_FILE)
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp 32 $(INPUT_SIZE) dqmom_input dqmom-32 dqmom_output_32 dqmom-128 dqmom_output_128  

test-pso: create-base-conf input_ranges_generator
	@echo RT = PSO >> s3fp_setting 
	@echo "==== generate input ranges ===="
	@input_ranges_generator $(INPUT_SIZE) $(INPUT_RANGE_FILE)
	@echo "==== run s3fp ===="
	@$(S3FP_DIR)/s3fp 32 $(INPUT_SIZE) dqmom_input dqmom-32 dqmom_output_32 dqmom-128 dqmom_output_128  

clean:
	-rm dqmom-32 dqmom-64 dqmom-128
	-rm dqmom_input*
	-rm dqmom_output_*
	-rm __outdump
	-rm best_input
	-rm *-input-ranges
	-rm input_ranges_generator